# numpy tutorial in python

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,5,6,7,8,7,7,2]] , np.int8)

In [3]:
myarr

array([[3, 4, 5, 6, 7, 8, 7, 7, 2]], dtype=int8)

In [6]:
myarr.shape

(1, 9)

In [7]:
myarr.dtype

dtype('int8')

In [8]:
myarr[0 , 1]

np.int8(4)

In [9]:
myarr[ 0 , 3] = 77

In [10]:
myarr

array([[ 3,  4,  5, 77,  7,  8,  7,  7,  2]], dtype=int8)

# other array creation in numpy python

In [11]:
listarr = np.array([[3,4,5] , [5,6,7] , [65,4,34]])

In [12]:
listarr

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [65,  4, 34]])

In [13]:
listarr.dtype

dtype('int64')

In [14]:
listarr.shape

(3, 3)

In [15]:
listarr.size

9

In [16]:
np.array({34,54,3})

array({34, 3, 54}, dtype=object)

In [17]:
zeros = np.zeros((3 , 3))

In [18]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(3, 3)

In [21]:
rng = np.arange(21)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [23]:
linspace = np.linspace(0,9,8)

In [24]:
linspace

array([0.        , 1.28571429, 2.57142857, 3.85714286, 5.14285714,
       6.42857143, 7.71428571, 9.        ])

In [25]:
lspace = np.linspace(3,4,6)

In [26]:
lspace

array([3. , 3.2, 3.4, 3.6, 3.8, 4. ])

In [27]:
enp = np.empty((2,7))

In [28]:
enp

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [29]:
penp = np.empty((6,4))

In [30]:
penp

array([[4.67296746e-307, 1.69121096e-306, 4.00535364e-307,
        1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306],
       [1.29060871e-306, 2.22518251e-306, 1.33511969e-306,
        1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.02361614e-306,
        1.78020848e-306],
       [1.78021527e-306, 1.69119330e-306, 9.79101082e-307,
        1.78020576e-306]])

In [31]:
ide = np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
ide.shape

(45, 45)

In [34]:
nodeide = np.identity(4)

In [35]:
nodeide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
nodeide.shape

(4, 4)

In [37]:
my_arr = np.arange(100)

In [38]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
my_arr.reshape(5 , 20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [40]:
my_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
x = [[1,2,3] , [4,5,6] , [7,1,0]]

In [42]:
arr = np.array(x)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.sum(axis = 0)

array([12,  8,  9])

In [45]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [46]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [48]:
arr.ndim

2

In [49]:
arr.size

9

In [50]:
arr.nbytes

72

In [51]:
hunt = np.array([2,3,4,566,73,4])

In [52]:
hunt.argmax()

np.int64(3)

In [53]:
hunt.argmin()

np.int64(0)

In [54]:
hunt.argsort()

array([0, 1, 2, 5, 4, 3])

In [55]:
hunt.dtype

dtype('int64')

In [56]:
trp = np.array([[2,3,4],[6,5,7],[77,65,45]])

In [57]:
trp.argmax(axis = 0)

array([2, 2, 2])

In [58]:
trp.argsort(axis = 1)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]])

In [59]:
trp.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [60]:
trp.reshape(9 , 1)

array([[ 2],
       [ 3],
       [ 4],
       [ 6],
       [ 5],
       [ 7],
       [77],
       [65],
       [45]])

In [61]:
arr1 = np.array([[23,3],[45,6],[56,76]])

In [62]:
arr2 = np.array([[45,3],[7,5],[23,33]])

In [63]:
arr1 + arr2

array([[ 68,   6],
       [ 52,  11],
       [ 79, 109]])

In [64]:
allarr = arr1 * arr2

In [65]:
np.sqrt(arr1)

array([[4.79583152, 1.73205081],
       [6.70820393, 2.44948974],
       [7.48331477, 8.71779789]])

In [66]:
allarr

array([[1035,    9],
       [ 315,   30],
       [1288, 2508]])

In [67]:
allarr.sum()

np.int64(5185)

In [68]:
allarr.max()

np.int64(2508)

In [69]:
np.where(allarr > 9)

(array([0, 1, 1, 2, 2]), array([0, 0, 1, 0, 1]))

In [70]:
np.where(allarr < 9)

(array([], dtype=int64), array([], dtype=int64))

In [71]:
np.count_nonzero(allarr)

6

In [72]:
import sys

In [73]:
py_arr = [4,45,4,5,554]

In [74]:
ch_arr = np.array(py_arr)

In [75]:
sys.getsizeof(1) * len(py_arr)

140

In [76]:
ch_arr.itemsize * ch_arr.size

40

In [77]:
ch_arr.tolist()

[4, 45, 4, 5, 554]